spring:
  datasource:
    url: jdbc:mysql://teamdb.cx6acq2ikt1l.ap-northeast-2.rds.amazonaws.com:3306/DOH
    username: abc3
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: HTML

server:
  port: 8083